return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		require'nvim-treesitter.configs'.setup {
			highlight = { enable = true },
			indent = { enable = true },  
			auto_install = true,
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<cr>",
					node_incremental = "<cr>",
					scope_incremental = false,
					node_decremental = "<bs>",
				},
			},
			ensure_installed = {
				"go",
				"angular",
				"asm",
				"awk",
				"bash",
				"c",
				"comment",
				"css",
				"csv",
				"dart",
				"diff",
				"dockerfile",
				"git_config",
				"git_rebase",
				"gitcommit",
				"gitignore",
				"go",
				"gomod",
				"gosum",
				"gowork",
				"hcl",
				"json",
				"make",
				"markdown",
				"python",
				"rust",
				"sql",
				"templ",
				"toml",
				"typescript",
				"xml",
				"yaml",
				"lua",
				"vim",
				"vimdoc",
				"query",
				"javascript",
				"html"
			},
		}
	end
}
